### ISSUE TITLE
develop(back): doFunction('가상데스크톱')

### ISSUE THREAD

**Issue by darkenergy814** [HICC-Bootcamp/2022-2-JHKim-gesture_recognition_program#1]
가상 데스크톱을 실행할 경우 프로그램이 새로 생성된 가상 데스크톱에선 프로그램이 없다. 따라서, 새로 생성된 가상 데스크톱에서 프로그램을 별도로 실행시켜야 프로그램이 작동한다.

**Comment by Guardian-demoN** [comment]
여기서 명시되고 있는 "가상 데스크톱"과 "프로그램"에 대한 명시가 필요해 보입니다.
프로그램이라면 실행 환경을 말씀하시는 것 같은데, 맞나요?

**Comment by darkenergy814** [comment]
아, 답변이 늦었네요. "가상 데스크톱"은 윈도우에서의 "가상 데스크톱"이고 "프로그램"은 저희가 만들 프로그램입니다.

**Comment by Guardian-demoN** [comment]
내용 확인했습니다. 가상 데스크톱이 무언가 했더니 데스크톱 하나 더 만드는 그 기능을 두고 가상 데스크톱이라 한 거였군요.
